### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sihengz02** [williamljb/DifferentiableCloth#11]
When I run demo_gravity, I encounter error below:

>Traceback (most recent call last):
  File "demo_gravity.py", line 2, in <module>
    import arcsim
ImportError: /home/siheng/miniconda3/envs/diffcloth/lib/python3.6/site-packages/arcsim-0.0.0-py3.6-linux-x86_64.egg/arcsim.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

My platform is Ubuntu20.04 and I my gcc/g++ version is both 8.4.0.

**Comment by sihengz02** [comment]
> 
And can you specify which version of libtorch do you install? I'm not sure whether I need to use libtorch 1.0.1?

**Comment by sihengz02** [comment]
If I use libtorch 1.0.1, which is the same version of pytorch, then I will encounter:

>arcsim/src/dde.cpp:115:66: error: too many arguments to function ‘at::Tensor at::grid_sampler(const at::Tensor&, const at::Tensor&, int64_t, int64_t)’
  115 |     Tensor actual_ke1 = relu(grid_sampler(bend, grid1, 0, 2, true).squeeze());

This error I think comes from low version libtorch do not have the last bool param, so I can not pass the compile.

But if I use the lst-version of libtorch, which is 1.8.2+cu102, I can pass the compile, but I will encounter error when I run the demo:
> Traceback (most recent call last):
File "demo_gravity.py", line 2, in
import arcsim
ImportError: /home/siheng/miniconda3/envs/diffcloth/lib/python3.6/site-packages/arcsim-0.0.0-py3.6-linux-x86_64.egg/arcsim.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

**Comment by sihengz02** [comment]
Solved by using both pytorch 1.8.1 and libtorch 1.8.1 and cuda 10.2 instead of using pytorch 1.0.1 and cuda 9.2.148
